include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_use_package_imports: true
    directives_ordering: true
    sort_pub_dependencies: false
    unnecessary_lambdas: true
    use_key_in_widget_constructors: true
    eol_at_end_of_file: true
    cancel_subscriptions: true
    close_sinks: true
