name: offline_pdf_document_scanner
description: Offline PDF Document Scanner — fully offline document capture, edit, OCR (optional), and PDF export.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  go_router: ^16.1.0
  camera: ^0.11.2
  image: ^4.2.0
  edge_detection: ^1.1.3
  image_cropper: 9.1.0
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^11.1.0
  google_mlkit_text_recognition: ^0.15.0
  uuid: ^4.5.1
  collection: ^1.18.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  in_app_purchase: ^3.2.3
  in_app_purchase_platform_interface: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  freezed: ^3.2.0
  json_serializable: ^6.9.0
  golden_toolkit: ^0.15.0
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
